In [1]:
import numpy as np
import pandas as pd
import scipy.linalg as la
import scipy.optimize as opt
import copy
np.set_printoptions(threshold=np.inf, suppress=True, formatter={'float': '{: 0.8f}'.format}, linewidth=75)

In [2]:
test_matrix = np.array([[1, 2], [3, 4]])
matr2 = np.array([[5, 6], [7, 8]])
big_test_matrix = la.block_diag(test_matrix, test_matrix)
readable_big_test_matrix = pd.DataFrame(big_test_matrix)
print(type(big_test_matrix))

<class 'numpy.ndarray'>


In [3]:
def kron(A, B):
    return la.kron(A, B)

In [4]:
def kronsum(A, B):
    if A.shape[0] != A.shape[1]:
        raise ValueError('A is not square')

    if B.shape[0] != B.shape[1]:
        raise ValueError('B is not square')
    
    L = kron(A, np.eye(B.shape[0]))
    R = kron(np.eye(A.shape[0]), B)
    
    return L+R

In [5]:
print(kronsum(test_matrix, matr2))

In [6]:
print(kronsum(big_test_matrix[:2, :2], big_test_matrix[2:4, 2:4]))

[[ 2.00000000  2.00000000  2.00000000  0.00000000]
 [ 3.00000000  5.00000000  0.00000000  2.00000000]
 [ 3.00000000  0.00000000  5.00000000  2.00000000]
 [ 0.00000000  3.00000000  3.00000000  8.00000000]]


In [7]:
n = 3
p_num = 100
eps_G = 10 ** (-8)
eps_Phi = 10 ** (-6)
eps_p_i = 10 ** (-6)

In [8]:
# Входной BMAP
matrD_0 = np.array([[-86., 0.01], [0.02, -2.76]]) / 7
matrD = np.array([[85, 0.99], [0.2, 2.54]]) / 7
matrD_k = [matrD_0]

W_ = matrD_0.shape[0]
W = W_ - 1

q = 0.8
for k in range(1, n+1):
    matrD_k.append(matrD * (q ** (k-1)) * (1 - q) / (1 - q ** 3))

for matr in matrD_k:
    print(matr)

[[-12.28571429  0.00142857]
 [ 0.00285714 -0.39428571]]
[[ 4.97658080  0.05796253]
 [ 0.01170960  0.14871194]]
[[ 3.98126464  0.04637002]
 [ 0.00936768  0.11896956]]
[[ 3.18501171  0.03709602]
 [ 0.00749415  0.09517564]]


In [9]:
# Характеристики входного BMAP

matrD_1_ = np.zeros(matrD_k[0].shape)
for matr in matrD_k:
    matrD_1_ += matr
print(matrD_1_)
matr_a = copy.deepcopy(matrD_1_)
for i in range(matr_a.shape[0]):
    matr_a[i][0] = 1

matr_b = np.zeros((matr_a.shape[0], 1))
matr_b[0][0] = 1

matr_a = np.transpose(matr_a)

theta = la.solve(matr_a, matr_b).reshape(-1)

matrdD_1_ = copy.deepcopy(matrD_k[1])

print(theta)

for i in range(2, n+1):
    matrdD_1_ += matrD_k[i] * i
vect_e = np.array([[1.] for i in range(0, matrD_1_.shape[0])])
lamD = np.dot(np.dot(theta, matrdD_1_), vect_e)
print(lamD)

[[-0.14285714  0.14285714]
 [ 0.03142857 -0.03142857]]
[ 0.18032787  0.81967213]
[ 4.69791416]


In [10]:
# Поток поломок MAP
matrH0 = np.array([[-8.110725, 0], [0, -0.26325]])
matrH1 = np.array([[8.0568, 0.053925], [0.146625, 0.116625]])
V_ = matrH1.shape[0]
V = V_ - 1
matrH = matrH0 + matrH1
matr_a = copy.deepcopy(matrH)
for i in range(matr_a.shape[0]):
    print(matr_a)
    matr_a[i][0] = 1
    
matr_b = np.zeros((matr_a.shape[0], 1))
matr_b[0][0] = 1

matr_a = np.transpose(matr_a)

print(matr_a)

gamma = la.solve(matr_a, matr_b).reshape(-1)

vect_e = np.array([[1.] for i in range(0, matrD_1_.shape[0])])
h = np.dot(np.dot(gamma, matrH1), vect_e)
print(h)

[[-0.05392500  0.05392500]
 [ 0.14662500 -0.14662500]]
[[ 1.00000000  0.05392500]
 [ 0.14662500 -0.14662500]]
[[ 1.00000000  1.00000000]
 [ 0.05392500 -0.14662500]]
[ 6.00065225]


In [11]:
# Поток обслуживания PH1
beta1 = np.matrix([1, 0])
matrS1 = np.matrix([[-20, 20], [0, -20]])
M1 = matrS1.shape[0]
M1_ = M1 + 1
M1_e = np.matrix([[1], [1]])
matrS1_0 = - matrS1 * M1_e
vect_e = np.array([[1.] for i in range(0, matrS1.shape[0])])
print(np.dot(beta1, la.inv(matrS1)))
mu_1 = -la.inv(np.dot(np.dot(beta1, la.inv(matrS1)), vect_e))
print(mu_1)

[[-0.05000000 -0.05000000]]
[[ 10.00000000]]


In [12]:
# Поток обслуживания PH2
beta2 = np.matrix([1, 0])
matrS2 = np.matrix([[-2, 2], [0, -2]])
M2 = matrS2.shape[0]
M2_ = M2 + 1
M2_e = np.matrix([[1], [1]])
matrS2_0 = np.dot(- matrS2, M2_e)

vect_e = np.array([[1.] for i in range(0, matrS2.shape[0])])
mu_2 = -la.inv(np.dot(np.dot(beta2, la.inv(matrS2)), vect_e))
print(mu_2)

[[ 1.00000000]]


In [13]:
matrS_w = kron(np.dot(matrS1_0, beta1), 
               np.dot(M2_e, beta2)) + kron(np.dot(M1_e, beta1), np.dot(matrS2_0, beta2))

In [14]:
# Поток переключения с прибора-1 на прибор-2
alpha1 = np.matrix([0.05, 0.95])
matrA1 = np.matrix([[-1.86075, 0.], [0., -146.9994]])
L1 = matrA1.shape[0]
L1_ = L1 + 1
L1_e = np.matrix([[1], [1]])
matrA1_0 = - np.dot(matrA1, L1_e)

vect_e = np.array([[1.] for i in range(0, matrA1.shape[0])])
kappa_1 = -la.inv(np.dot(np.dot(alpha1, la.inv(matrA1)), vect_e))
print(kappa_1)

[[ 29.99985287]]


In [15]:
# Поток переключения с прибора-2 на прибор-1
alpha2 = np.matrix([0.05, 0.95])
matrA2 = np.matrix([[-5.58225, 0.], [0., -440.9982]])
L2 = matrA2.shape[0]
L2_ = L2 + 1
L2_e = np.matrix([[1], [1]])
matrA2_0 = - np.dot(matrA2, L2_e)

vect_e = np.array([[1.] for i in range(0, matrA1.shape[0])])
kappa_2 = -la.inv(np.dot(np.dot(alpha2, la.inv(matrA2)), vect_e))
print(kappa_2)

[[ 89.99955862]]


In [16]:
# Поток ремонта PH
tau = np.matrix([0.98, 0.02])
matrT = np.matrix([[-100., 0.], [0., -0.0002]])
T_e = np.matrix([[1], [1]])
matrT0 = - np.dot(matrT, T_e)

R = matrT.shape[0]
R_ = R + 1
vect_e = np.array([[1.] for i in range(0, matrT.shape[0])])
phi = -np.dot(np.dot(tau, la.inv(matrT)), vect_e)
print(phi)

[[ 100.00980000]]


In [16]:
a = W_ * V_

In [18]:
print(kronsum(matrD_k[0], matrH0))

[[-20.39643929  0.00000000  0.00142857  0.00000000]
 [ 0.00000000 -12.54896429  0.00000000  0.00142857]
 [ 0.00285714  0.00000000 -8.50501071  0.00000000]
 [ 0.00000000  0.00285714  0.00000000 -0.65753571]]


In [52]:
# Q~0
block00 = kronsum(matrD_k[0], matrH0)
block03 = kron(kron(kron(np.eye(W_), matrH1), tau), alpha1)
block10 = kron(np.eye(a), matrA2_0)
block11 = kronsum(kronsum(matrD_k[0], matrH0), matrA2)
block12 = kron(kron(kron(np.eye(W_), matrH1), tau), L2_e)
block21 = kron(kron(np.eye(a), matrT0), alpha2)
block22 = kronsum(kronsum(matrD_k[0], matrH), matrT)
block30 = kron(kron(np.eye(a), matrT0), L1_e)
block32 = kron(kron(np.eye(a), np.eye(R)), matrA1_0)
block33 = kronsum(kronsum(kronsum(matrD_k[0], matrH), matrT), matrA1)
block01 = np.zeros((block00.shape[0], block11.shape[1]))
block02 = np.zeros((block00.shape[0], block12.shape[1]))
block13 = np.zeros((block10.shape[0], block03.shape[1]))
block20 = np.zeros((block21.shape[0], block10.shape[1]))
block23 = np.zeros((block21.shape[0], block03.shape[1]))
block31 = np.zeros((block30.shape[0], block11.shape[1]))

print(block30.shape)

matrQw_0 = np.bmat([[block00, block01, block02, block03],
                    [block10, block11, block12, block13], 
                    [block20, block21, block22, block23],
                    [block30, block31, block32, block33]])
print(matrQw_0.shape)

(16, 4)
(36, 36)


In [42]:
# Q~k
matrQw_k = [matrQw_0]
for i in range(1, n+1):
    block0 = kron(kron(matrD_k[i], np.eye(V_)), beta1)
    block1 = kron(kron(kron(matrD_k[i], np.eye(V_)), beta2), np.eye(L2))
    block2 = kron(kron(kron(matrD_k[i], np.eye(V_)), beta2), np.eye(R))
    block3 = kron(kron(matrD_k[i], np.eye(V_)), np.eye(R*L1))
    matr_temp = la.block_diag(block0, block1, block2, block3)
    matrQw_k.append(matr_temp)
    
print(matrQw_k[0].shape)
print(matrQw_k[1].shape)

for i in range(matrQw_k[0].shape[0]):
    sum = 0
    for matr in matrQw_k:
        sum += np.sum(matr[i])
    print('matrQw_k[' + str(i) + '] = ', sum)

(36, 36)
(36, 56)
matrQw_k[0] =  8.881784197e-16
matrQw_k[1] =  8.881784197e-16
matrQw_k[2] =  5.55111512313e-16
matrQw_k[3] =  1.11022302463e-16
matrQw_k[4] =  -4.4408920985e-15
matrQw_k[5] =  -8.881784197e-16
matrQw_k[6] =  2.6645352591e-15
matrQw_k[7] =  -5.77315972805e-14
matrQw_k[8] =  2.22044604925e-16
matrQw_k[9] =  -1.487698853e-14
matrQw_k[10] =  0.0
matrQw_k[11] =  1.42108547152e-14
matrQw_k[12] =  8.881784197e-16
matrQw_k[13] =  -8.881784197e-16
matrQw_k[14] =  -6.2172489379e-15
matrQw_k[15] =  -8.881784197e-16
matrQw_k[16] =  6.88338275268e-15
matrQw_k[17] =  6.10622663544e-16
matrQw_k[18] =  -8.881784197e-16
matrQw_k[19] =  1.11022302463e-16
matrQw_k[20] =  1.33226762955e-14
matrQw_k[21] =  -1.50990331349e-14
matrQw_k[22] =  8.881784197e-16
matrQw_k[23] =  8.881784197e-16
matrQw_k[24] =  -2.6645352591e-15
matrQw_k[25] =  7.9936057773e-15
matrQw_k[26] =  -8.881784197e-16
matrQw_k[27] =  7.9936057773e-15
matrQw_k[28] =  2.27595720048e-15
matrQw_k[29] =  3.06976666309e-14
mat

In [43]:
# Q^0
block0 = kron(np.eye(a), matrS1_0)
block1 = kron(kron(np.eye(a), matrS2_0), np.eye(L2))
block2 = kron(kron(np.eye(a), matrS2_0), np.eye(R))
block3 = np.zeros((a*R*L1, a*R*L1))
matrQv_0 = la.block_diag(block0, block1, block2, block3)

print(matrQv_0.shape)

(56, 36)


In [44]:
# Q_0
block0 = kron(np.eye(a), np.dot(matrS1_0, beta1))
block1 = kron(kron(np.eye(a), np.dot(matrS2_0, beta2)), np.eye(L2))
block2 = kron(kron(np.eye(a), np.dot(matrS2_0, beta2)), np.eye(R))
block3 = np.zeros((a*R*L1, a*R*L1))
matrQ_0 = la.block_diag(block0, block1, block2, block3)

print(matrQ_0.shape)

(56, 56)


In [45]:
# Q_1
block00 = kronsum(kronsum(matrD_k[0], matrH0), matrS1)
block03 = kron(kron(kron(kron(np.eye(W_), matrH1), M1_e), tau), alpha1)
block10 = kron(kron(kron(np.eye(a), M2_e), beta1), matrA2_0)
block11 = kronsum(kronsum(kronsum(matrD_k[0], matrH0), matrS2), matrA2)
block12 = kron(kron(kron(kron(np.eye(W_), matrH1), np.eye(M2)), tau), L2_e)
block21 = kron(kron(kron(np.eye(a), np.eye(M2)), matrT0), alpha1)
block22 = kronsum(kronsum(kronsum(matrD_k[0], matrH), matrS2), matrT)
block30 = kron(kron(kron(np.eye(a), beta1), matrT0), L1_e)
block32 = kron(kron(kron(np.eye(a), beta2), np.eye(R)), matrA1_0)
block33 = kronsum(kronsum(kronsum(matrD_k[0], matrH), matrT), matrA1)
block01 = np.zeros((block00.shape[0], block11.shape[1]))
block02 = np.zeros((block00.shape[0], block12.shape[1]))
block13 = np.zeros((block10.shape[0], block03.shape[1]))
block20 = np.zeros((block21.shape[0], block10.shape[1]))
block23 = np.zeros((block21.shape[0], block03.shape[1]))
block31 = np.zeros((block30.shape[0], block11.shape[1]))

matrQ_1 = np.bmat([[block00, block01, block02, block03], 
                   [block10, block11, block12, block13], 
                   [block20, block21, block22, block23], 
                   [block30, block31, block32, block33]])

print(matrQ_1.shape)

(56, 56)


In [24]:
matrQ_k = [matrQ_0, matrQ_1]
for k in range(2, n+2):
    block0 = kron(matrD_k[k-1], np.eye(V_ * M1))
    block1 = kron(matrD_k[k-1], np.eye(V_*M2*L2))
    block2 = kron(matrD_k[k-1], np.eye(V_*M2*R))
    block3 = kron(matrD_k[k-1], np.eye(V_*R*L1))
    matr_temp = la.block_diag(block0, block1, block2, block3)
    matrQ_k.append(matr_temp)

for i in range(matrQ_k[0].shape[0]):
    sum = np.sum(matrQv_0[i])
    for j in range(1, np.array(matrQ_k).shape[0]):
        sum += np.sum(matrQ_k[j][i])
    print('matrQ_k[' + str(i) + '] = ', sum)

matrQ_k[0] =  8.881784197e-16
matrQ_k[1] =  -7.9936057773e-15
matrQ_k[2] =  2.6645352591e-15
matrQ_k[3] =  -8.881784197e-16
matrQ_k[4] =  5.55111512313e-17
matrQ_k[5] =  -1.72084568817e-15
matrQ_k[6] =  1.49880108324e-15
matrQ_k[7] =  1.83186799063e-15
matrQ_k[8] =  8.881784197e-16
matrQ_k[9] =  6.2172489379e-15
matrQ_k[10] =  -2.6645352591e-15
matrQ_k[11] =  6.2172489379e-15
matrQ_k[12] =  4.4408920985e-15
matrQ_k[13] =  -5.77315972805e-14
matrQ_k[14] =  4.4408920985e-15
matrQ_k[15] =  -5.77315972805e-14
matrQ_k[16] =  -8.32667268469e-16
matrQ_k[17] =  -3.36952687974e-14
matrQ_k[18] =  -1.72084568817e-15
matrQ_k[19] =  -3.36952687974e-14
matrQ_k[20] =  -1.66533453694e-16
matrQ_k[21] =  -5.49560397189e-15
matrQ_k[22] =  5.55111512313e-17
matrQ_k[23] =  -5.27355936697e-15
matrQ_k[24] =  6.2172489379e-15
matrQ_k[25] =  -8.881784197e-16
matrQ_k[26] =  6.2172489379e-15
matrQ_k[27] =  -8.881784197e-16
matrQ_k[28] =  -8.881784197e-16
matrQ_k[29] =  -8.881784197e-16
matrQ_k[30] =  -8.88178419

In [24]:
# Проверка генератора Q

In [26]:
# Поиск матрицы G

matrQ_1_neg_inv = np.linalg.inv(-matrQ_k[1])


def calc_G(matrG_prev):
    temp_sum = copy.deepcopy(matrQ_k[0]) 
    for k in range(2, n + 2):
        temp_sum += np.dot(matrQ_k[k], np.linalg.matrix_power(matrG_prev, k))
    matrG_new = np.dot(matrQ_1_neg_inv, temp_sum)
    return matrG_new

matrG_old = np.eye(matrQ_k[1].shape[0])
matrG = calc_G(matrG_old)


i = 1
while la.norm(matrG - matrG_old, ord=np.inf) >= eps_G:
    matrG_old = matrG
    matrG = calc_G(matrG_old)
    i += 1
print(i)
pd.DataFrame(matrG).head()

372


<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>...</th>
      <th>46</th>
      <th>47</th>
      <th>48</th>
      <th>49</th>
      <th>50</th>
      <th>51</th>
      <th>52</th>
      <th>53</th>
      <th>54</th>
      <th>55</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.396833</td>
      <td>6.301116e-218</td>
      <td>0.002519</td>
      <td>5.119609e-218</td>
      <td>0.268151</td>
      <td>1.037783e-219</td>
      <td>0.244523</td>
      <td>7.465557e-220</td>
      <td>7.445429e-05</td>
      <td>2.186799e-05</td>
      <td>...</td>
      <td>3.043048e-221</td>
      <td>2.646388e-222</td>
      <td>9.720530e-222</td>
      <td>7.605106e-221</td>
      <td>1.285493e-221</td>
      <td>2.609363e-222</td>
      <td>1.527269e-223</td>
      <td>1.171485e-222</td>
      <td>5.763182e-223</td>
      <td>4.057573e-224</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.606271</td>
      <td>4.712764e-218</td>
      <td>0.001715</td>
      <td>3.829085e-218</td>
      <td>0.175245</td>
      <td>7.761839e-220</td>
      <td>0.159389</td>
      <td>5.583679e-220</td>
      <td>5.161550e-05</td>
      <td>1.516101e-05</td>
      <td>...</td>
      <td>2.275973e-221</td>
      <td>1.979301e-222</td>
      <td>7.270230e-222</td>
      <td>5.688051e-221</td>
      <td>9.614531e-222</td>
      <td>1.951609e-222</td>
      <td>1.142283e-223</td>
      <td>8.761831e-223</td>
      <td>4.310430e-223</td>
      <td>3.034762e-224</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.004480</td>
      <td>7.880094e-218</td>
      <td>0.483810</td>
      <td>6.402517e-218</td>
      <td>0.167202</td>
      <td>1.297838e-219</td>
      <td>0.289445</td>
      <td>9.336330e-220</td>
      <td>2.298020e-06</td>
      <td>6.712217e-07</td>
      <td>...</td>
      <td>3.805597e-221</td>
      <td>3.309539e-222</td>
      <td>1.215637e-221</td>
      <td>9.510848e-221</td>
      <td>1.607622e-221</td>
      <td>3.263236e-222</td>
      <td>1.909983e-223</td>
      <td>1.465044e-222</td>
      <td>7.207362e-223</td>
      <td>5.074349e-224</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.002866</td>
      <td>5.725894e-218</td>
      <td>0.695133</td>
      <td>4.652246e-218</td>
      <td>0.098474</td>
      <td>9.430447e-220</td>
      <td>0.171100</td>
      <td>6.784036e-220</td>
      <td>1.484291e-06</td>
      <td>4.338016e-07</td>
      <td>...</td>
      <td>2.765252e-221</td>
      <td>2.404802e-222</td>
      <td>8.833154e-222</td>
      <td>6.910845e-221</td>
      <td>1.168142e-221</td>
      <td>2.371158e-222</td>
      <td>1.387846e-223</td>
      <td>1.064541e-222</td>
      <td>5.237068e-223</td>
      <td>3.687162e-224</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.000589</td>
      <td>2.314830e-219</td>
      <td>0.000016</td>
      <td>1.880782e-219</td>
      <td>0.968647</td>
      <td>3.812485e-221</td>
      <td>0.009691</td>
      <td>2.742609e-221</td>
      <td>1.877517e-07</td>
      <td>3.480540e-08</td>
      <td>...</td>
      <td>1.117919e-222</td>
      <td>9.721990e-224</td>
      <td>3.571014e-223</td>
      <td>2.793875e-222</td>
      <td>4.722495e-223</td>
      <td>9.585974e-224</td>
      <td>5.610701e-225</td>
      <td>4.303664e-224</td>
      <td>2.117210e-224</td>
      <td>1.490624e-225</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 56 columns</p>
</div>

In [27]:
la.norm(matrG, ord=np.inf)

1.0000000017054

In [28]:
temp_sum = matrQ_k[1].copy()
for k in range(2, n+2):
    temp_sum += matrQ_k[k].dot(np.linalg.matrix_power(matrG, k-1))
matrG_0 = la.inv(temp_sum)
matrG_0 = (-matrG_0).dot(matrQv_0)
pd.DataFrame(matrG_0)

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>...</th>
      <th>26</th>
      <th>27</th>
      <th>28</th>
      <th>29</th>
      <th>30</th>
      <th>31</th>
      <th>32</th>
      <th>33</th>
      <th>34</th>
      <th>35</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.396833</td>
      <td>0.002519</td>
      <td>0.268151</td>
      <td>0.244523</td>
      <td>7.445429e-05</td>
      <td>2.186799e-05</td>
      <td>1.023466e-06</td>
      <td>1.736665e-07</td>
      <td>0.000140</td>
      <td>1.769089e-05</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.606271</td>
      <td>0.001715</td>
      <td>0.175245</td>
      <td>0.159389</td>
      <td>5.161550e-05</td>
      <td>1.516101e-05</td>
      <td>7.092874e-07</td>
      <td>1.203822e-07</td>
      <td>0.000092</td>
      <td>1.156039e-05</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.004480</td>
      <td>0.483810</td>
      <td>0.167202</td>
      <td>0.289445</td>
      <td>2.298020e-06</td>
      <td>6.712217e-07</td>
      <td>2.023818e-06</td>
      <td>3.154654e-07</td>
      <td>0.000088</td>
      <td>1.116733e-05</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.002866</td>
      <td>0.695133</td>
      <td>0.098474</td>
      <td>0.171100</td>
      <td>1.484291e-06</td>
      <td>4.338016e-07</td>
      <td>1.315272e-06</td>
      <td>2.050693e-07</td>
      <td>0.000052</td>
      <td>6.577608e-06</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.000589</td>
      <td>0.000016</td>
      <td>0.968647</td>
      <td>0.009691</td>
      <td>1.877517e-07</td>
      <td>3.480540e-08</td>
      <td>4.267502e-09</td>
      <td>2.856422e-10</td>
      <td>0.000491</td>
      <td>6.273390e-05</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.000387</td>
      <td>0.000009</td>
      <td>0.981642</td>
      <td>0.005646</td>
      <td>1.142628e-07</td>
      <td>2.160944e-08</td>
      <td>2.560749e-09</td>
      <td>1.769470e-10</td>
      <td>0.000288</td>
      <td>3.687099e-05</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.000021</td>
      <td>0.000694</td>
      <td>0.015557</td>
      <td>0.982532</td>
      <td>8.357641e-09</td>
      <td>1.808865e-09</td>
      <td>7.072446e-09</td>
      <td>4.638857e-10</td>
      <td>0.000016</td>
      <td>1.987886e-06</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <t

In [62]:
matrQ_il = []
for i in range(0, p_num):
    matrQ_il.append([])
    if i == 0:
        for l in range(0, n + 1):
            # здесь до n, т.к. нет больше матриц Q_k
            temp_matr = matrQw_k[l].copy()
            for k in range(l + 1, n + 1):
                mult_matr = matrQw_k[k].copy()
                for kk in range(k - 1, l - 1, -1):
                    if kk == 0:
                        mult_matr = mult_matr.dot(matrG_0)
                    else:
                        mult_matr = mult_matr.dot(matrG)
                print("mult matr 0 shape : ", mult_matr.shape)
                temp_matr += mult_matr
            matrQ_il[i].append(temp_matr)
        for l in range(n + 1, p_num):
            matrQ_il[i].append(np.zeros(matrQw_k[1].shape))
    else:
        for l in range(0, p_num):
            if l >= i and (l - i) <= (n + 1):
                if (l - i + 1) <= (n + 1): 
                    temp_matr = copy.deepcopy(matrQ_k[l - i + 1])
                else:
                    temp_matr = np.zeros(matrQ_k[0].shape)
                    
                for k in range(l + 1, p_num):  # sum from l+1 to inf
                    if (k - i) <= (n + 1):
                        mult_matr = copy.deepcopy(matrQ_k[k - i])
                        for kk in range(l, k):
                            mult_matr = np.dot(mult_matr, matrG)
                        
                        temp_matr += mult_matr
                matrQ_il[i].append(temp_matr)
            else:
                matrQ_il[i].append(np.zeros(matrQ_k[0].shape))

# print(len(matrQ_il[3]))
print(matrQ_il[4][4].shape)

mult matr 0 shape :  (36, 36)
mult matr 0 shape :  (36, 36)
mult matr 0 shape :  (36, 36)
mult matr 0 shape :  (36, 56)
mult matr 0 shape :  (36, 56)
mult matr 0 shape :  (36, 56)


(56, 56)


In [63]:
matrPhi_0 = np.eye(matrQ_il[0][0].shape[0])
matrPhi_l = [matrPhi_0]
for l in range(1, p_num):
    temp_matr = np.dot(np.dot(matrPhi_l[0], matrQ_il[0][l]), la.inv(-matrQ_il[l][l]))
    for i in range(1, l):
        # print(matrPhi_l[i].dot(matrQ_il[i][l]).dot(la.inv(-matrQ_il[l][l])).shape)
        temp_matr += np.dot(np.dot(matrPhi_l[i], matrQ_il[i][l]), la.inv(-matrQ_il[l][l]))
    matrPhi_l.append(temp_matr)

l =  1
l =  2
l =  3
l =  4
l =  5
l =  6
l =  7
l =  8
l =  9
l =  10
l =  11
l =  12
l =  13
l =  14
l =  15
l =  16
l =  17
l =  18


l =  19
l =  20
l =  21
l =  22
l =  23
l =  24
l =  25
l =  26


l =  27
l =  28
l =  29
l =  30
l =  31
l =  32
l =  33
l =  34
l =  35
l =  36
l =  37
l =  38


l =  39
l =  40
l =  41
l =  42


l =  43
l =  44
l =  45
l =  46
l =  47
l =  48
l =  49


l =  50
l =  51
l =  52
l =  53
l =  54


l =  55
l =  56
l =  57
l =  58
l =  59
l =  60


l =  61
l =  62
l =  63


l =  64
l =  65
l =  66
l =  67


l =  68
l =  69
l =  70
l =  71


l =  72
l =  73
l =  74
l =  75
l =  76


l =  77
l =  78
l =  79
l =  80
l =  81


l =  82
l =  83
l =  84
l =  85


l =  86
l =  87
l =  88
l =  89
l =  90


l =  91
l =  92
l =  93
l =  94


l =  95
l =  96
l =  97
l =  98


l =  99


In [33]:
matr_a = - copy.deepcopy(matrQ_il[0][0])
for i in range(matr_a.shape[0]):
    matr_a[i][0] = 1

matr_b = np.zeros((matr_a.shape[0], 1))
matr_b[0][0] = 1
matr_a = np.transpose(matr_a)
p0 = la.solve(matr_a, matr_b).reshape(-1)

print(p0)
print(p0.sum())

LinAlgError: singular matrix

In [31]:
vect_p_l = [p0]
for l in range(1, p_num):
    vect_p_l.append(vect_p_l[0].dot(matrPhi_l[l]))
    print(vect_p_l[l])

NameError: name 'p0' is not defined

In [32]:
# Условие эргодичности
block00 = kronsum(matrH0, matrS1) + kron(np.eye(V_), matrS1_0.dot(beta1))
block03 = kron(kron(kron(matrH1, M1_e), tau), alpha1)
block10 = kron(kron(np.eye(V_), M2_e.dot(beta1)), matrA2_0)
block11 = kronsum(kronsum(matrH0, matrS2), matrA2) + kron(kron(np.eye(V_), matrS2_0.dot(beta2)), np.eye(L2))
block12 = kron(kron(kron(matrH1, np.eye(M2)), tau), L2_e)
block21 = kron(kron(kron(np.eye(V_), np.eye(M2)), matrT0), alpha1)
block22 = kronsum(kronsum(matrH, matrS2), matrT) + kron(kron(np.eye(V_), matrS2_0.dot(beta2)), np.eye(R))
block30 = kron(kron(kron(np.eye(V_), beta1), matrT0), L1_e)
block32 = kron(kron(kron(np.eye(V_), beta2), np.eye(R)), matrA1_0)
block33 = kronsum(kronsum(matrH, matrT), matrA1)
block01 = np.zeros((block00.shape[0], block11.shape[1]))
block02 = np.zeros((block00.shape[0], block12.shape[1]))
block13 = np.zeros((block10.shape[0], block03.shape[1]))
block20 = np.zeros((block21.shape[0], block00.shape[1]))
block23 = np.zeros((block21.shape[0], block03.shape[1]))
block31 = np.zeros((block30.shape[0], block11.shape[1]))
matrGamma = np.bmat([[block00, block01, block02, block03],
                     [block10, block11, block12, block13],
                     [block20, block21, block22, block23],
                     [block30, block31, block32, block33]])
pd.DataFrame(matrGamma)

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>...</th>
      <th>18</th>
      <th>19</th>
      <th>20</th>
      <th>21</th>
      <th>22</th>
      <th>23</th>
      <th>24</th>
      <th>25</th>
      <th>26</th>
      <th>27</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-28.110725</td>
      <td>0.000000</td>
      <td>20.00000</td>
      <td>0.00000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.394783</td>
      <td>7.500881</td>
      <td>0.008057</td>
      <td>0.153079</td>
      <td>0.002642</td>
      <td>0.050204</td>
      <td>0.000054</td>
      <td>0.001025</td>
    </tr>
    <tr>
      <th>1</th>
      <td>20.000000</td>
      <td>-28.110725</td>
      <td>0.00000</td>
      <td>20.00000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.394783</td>
      <td>7.500881</td>
      <td>0.008057</td>
      <td>0.153079</td>
      <td>0.002642</td>
      <td>0.050204</td>
      <td>0.000054</td>
      <td>0.001025</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>-20.26325</td>
      <td>0.00000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.007185</td>
      <td>0.136508</td>
      <td>0.000147</td>
      <td>0.002786</td>
      <td>0.005715</td>
      <td>0.108578</td>
      <td>0.000117</td>
      <td>0.002216</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>20.00000</td>
      <td>-20.26325</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.007185</td>
      <td>0.136508</td>
      <td>0.000147</td>
      <td>0.002786</td>
      <td>0.005715</td>
      <td>0.108578</td>
      <td>0.000117</td>
      <td>0.002216</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5.582250</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>-15.692975</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>2.00000</td>
      <td>0.00000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>440.998200</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>0.000000</td>
      <td>-15.692975</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>2.00000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>5.582250</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>2.000000</td>
      <td>0.000000</td>
      <td>-15.692975</td>
      <td>0.000000</td>
      <td>0.00000</td>
      <td>0.00000</td>
      <td>...</td>
      <t

In [33]:
matr_a = np.transpose(matrGamma)
matr_b = np.zeros((matr_a.shape[0], 1))
x = la.lstsq(matr_a, matr_b)[3]
vect_e = np.array([[1.] for i in range(0, x.shape[0])])
res = x.dot(vect_e)[0]
x /= res
print('x = ', x)
x1 = x[0:V_*M1]
x2 = x[V_*M1:V_*M1 + V_*M2*L2]
x3 = x[V_*M1 + V_*M2*L2: V_*M1 + V_*M2*L2 + V_*M2*R]

print('x1 = ', x1)
print('x2 = ', x2)
print('x3 = ', x3)

x =  [ 0.16664882  0.13778178  0.09753639  0.09537417  0.09494841  0.04665250
  0.04465977  0.04342233  0.04276691  0.03395629  0.03158904  0.03007703
  0.02191321  0.02187875  0.02159697  0.02112990  0.01512927  0.01121088
  0.00796851  0.00373772  0.00334295  0.00324881  0.00142412  0.00060284
  0.00058718  0.00052926  0.00025505  0.00003113]
x1 =  [ 0.16664882  0.13778178  0.09753639  0.09537417]
x2 =  [ 0.09494841  0.04665250  0.04465977  0.04342233  0.04276691  0.03395629
  0.03158904  0.03007703]
x3 =  [ 0.02191321  0.02187875  0.02159697  0.02112990  0.01512927  0.01121088
  0.00796851  0.00373772]


In [ ]:
e_V_ = np.array([[1.] for i in range(0, V_)])
e_R = np.array([[1.] for i in range(0, R)])
pi1 = x1.dot(kron(e_V_, np.eye(M1)))
pi2 = x2.dot(kron(kron(e_V_, np.eye(M2)), L2_e))
pi3 = x3.dot(kron(kron(e_V_, np.eye(M2)), e_R))
print('pi1 = ', pi1)
print('pi2 = ', pi2)
print('pi3 = ', pi3)

In [ ]:
rho = pi1.dot(matrS1_0) + (pi2 + pi3).dot(matrS2_0)
rho = rho.tolist()[0][0]
print('rho = ', rho)

In [ ]:
print(la.norm(np.eye(matrQ_il[0][0].shape[0]).dot(matrQ_il[0][1]).dot(la.inv(-matrQ_il[1][1])), np.inf))

In [ ]:
result = np.sum(matrQv_0[0])
i = 0
for matrQk in matrQ_k:
    if i > 0:
        result += np.sum(matrQk[0])
    i += 1
print(result)